import { test } from 'node:test';
import assert from 'node:assert';
import { parseGcode } from '../src/gcodeUtils.js';

test('parseGcode extracts relevant data', () => {
  const gcode = `; generated by BambuStudio\n; model printing time = 120\n; total filament weight = 23.23,5.3\n; enable_support = 1\n; filament_type = PLA,PA\n; layer_height = 0.2\n; nozzle_diameter = 0.4\n; sparse_infill_density = 15\n; printer_model = X1C\n`;
  assert.deepStrictEqual(parseGcode(gcode), {
    slicer: 'BambuStudio',
    modelPrintingTime: 2,
    totalFilamentWeight1: 23.23,
    totalFilamentWeight2: 5.3,
    enableSupport: true,
    filamentType1: 'PLA',
    filamentType2: 'PA',
    layerHeight: 0.2,
    nozzleDiameter: 0.4,
    sparseInfillDensity: 15,
    printerModel: 'X1C'
  });
});
