import { test } from 'node:test';
import assert from 'node:assert';
import { parseGcode } from '../src/gcodeUtils.js';

test('parseGcode extracts data from gcode comments', () => {
  const gcode = `; generated by BambuStudio
; model printing time: 3600
; total filament weight: 23.23,5.3
; enable_support: 1,0
; filament_type: PLA,PETG
; layer_height: 0.2
; nozzle_diameter: 0.4
; sparse_infill_density: 15
; printer_model: X1 Carbon`;
  assert.deepStrictEqual(parseGcode(gcode), {
    slicer: 'BambuStudio',
    modelPrintingTime: 60,
    totalFilamentWeight1: 23.23,
    totalFilamentWeight2: 5.3,
    enableSupport1: '1',
    enableSupport2: '0',
    filamentType1: 'PLA',
    filamentType2: 'PETG',
    layerHeight: 0.2,
    nozzleDiameter: 0.4,
    sparseInfillDensity: 15,
    printerModel: 'X1 Carbon'
  });
});
